name: Test Database and Backend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector mysql
    - name: Add sample data to Database
      run: cd tests && python dbTestFiller.py
    - name: Fetch Latest Curie-CLI
      run: docker pull navanchauhan/curie-cli:latest
    - name: Run Backend Test
      run: cd tests && python backendTest.py
    - name: Remove sample data
      run: cd tests && pyton removeSample.py
