name: Test Database and Backend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    env:
     CURIE_DB: ${{ secrets.CURIE_DB }}
     CURIE_EMAIL: ${{ secrets.CURIE_EMAIL }}
     CURIE_EMAIL_PASSWORD: ${{ secrets.CURIE_EMAIL_PASSWORD }}
     CURIE_EMAIL_PORT: ${{ secrets.CURIE_EMAIL_PORT }}
     CURIE_EMAIL_SERVER: ${{ secrets.CURIE_EMAIL_SERVER }}
     CURIE_HOST: ${{ secrets.CURIE_HOST }}
     CURIE_PASSWORD: ${{ secrets.CURIE_PASSWORD }}
     CURIE_PORT: ${{ secrets.CURIE_PORT }}
     CURIE_USER: ${{ secrets.CURIE_USER }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector mysql
    - name: Clean Test Data
      run: cd tests && python removeSample.py
    - name: Add sample data to Database
      run: cd tests && python dbTestFiller.py
    - name: Fetch Latest Curie-CLI
      run: docker pull navanchauhan/curie-cli:latest
    - name: Run Backend Test
      run: cd tests && python backendTest.py
    - name: Remove Sample Data
      run: cd tests && python removeSample.py
